Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -3,7 +3,7 @@ name: Deploy AWS Resources
 on:
   push:
     branches:
-      - main  # Change this to your main branch name
+      - main  
 
 jobs:
   deploy:
@@ -38,7 +38,6 @@ jobs:
             --template-url https://artifacts-cft-deploy.s3.ap-south-1.amazonaws.com/templates/sam_template.yml \
             --change-set-name $CHANGESET_NAME \
             --capabilities CAPABILITY_NAMED_IAM
-        # Replace with your own stack name, S3 URL, change set name, and parameters
 
       - name: Wait for ChangeSet to be Available
         run: |
@@ -51,7 +50,7 @@ jobs:
               exit 1
             else
               echo "ChangeSet status is $status. Waiting for completion..."
-              sleep 30  # Adjust the polling interval as needed
+              sleep 30  
             fi
           done
 
@@ -60,3 +59,18 @@ jobs:
           aws cloudformation execute-change-set \
             --stack-name Deploy-Resource \
             --change-set-name $CHANGESET_NAME
+
+      - name: Wait for Stack Execution to Complete
+        run: |
+          while true; do
+            status=$(aws cloudformation describe-stacks --stack-name Deploy-Resource --query "Stacks[0].StackStatus" --output text)
+            if [ "$status" == "CREATE_COMPLETE" ]; then
+              break
+            elif [ "$status" == "ROLLBACK_COMPLETE" ]; then
+              echo "Stack creation failed. Aborting."
+              exit 1
+            else
+              echo "Stack status is $status. Waiting for completion..."
+              sleep 30  # Adjust the polling interval as needed
+            fi
+          done
